"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sys
import json
import boto3
from botocore.exceptions import ClientError

# Load environment variables from a .env file
load_dotenv()  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 1. HELPER FUNCTION TO UNWRAP AWS SECRETS
def get_aws_secret(secret_arn):
    """Fetches and decodes a JSON secret from AWS Secrets Manager."""
    if not secret_arn:
        return {}
    
    # API Gateway/Lambda always injects AWS_REGION automatically
    region_name = os.getenv('AWS_REGION', 'eu-west-1') 
    client = boto3.client('secretsmanager', region_name=region_name)
    
    try:
        response = client.get_secret_value(SecretId=secret_arn)
        return json.loads(response['SecretString'])
    except Exception as e:
        print(f"CRITICAL: Failed to retrieve secret {secret_arn}. Error: {e}")
        return {}

# 2. RESOLVE CREDENTIALS
# If we are in Lambda, these ARNs will be populated. If local, they will be None.
db_secrets_arn = os.getenv('DATABASE_SECRET_ARN')
app_secrets_arn = os.getenv('APP_SECRETS_ARN')

# Fetch the dictionaries from AWS (or return empty dicts if local)
db_credentials = get_aws_secret(db_secrets_arn)
app_credentials = get_aws_secret(app_secrets_arn)

# 3. SET THE DJANGO SECRETS
# Fallback to standard os.getenv for local dev (.env file)
SECRET_KEY = app_credentials.get('SECRET_KEY') or os.getenv('SECRET_KEY', 'unsafe-dev-key')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restaurant',                   # The restaurant app
    'rest_framework',                # Django REST framework  
    'djoser',                      # Djoser for user management
    'rest_framework.authtoken',        # Token authentication
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database CONFIGURATION (Pivoted to Aurora Serverless PostgreSQL)
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 4. DATABASE ROUTING
if os.getenv('CI_MODE', 'False') == 'True' and not db_secrets_arn:
    # Fallback for GitHub Actions testing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Production Aurora Serverless Routing
    # AWS managed RDS secrets automatically provide 'username', 'password', 'host', and 'port'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'asgard_cuisines_db', # Hardcoded to match the database_name in db/main.tf
            'USER': db_credentials.get('username') or os.getenv('DB_USER'),
            'PASSWORD': db_credentials.get('password') or os.getenv('DB_PASSWORD'),
            'HOST': db_credentials.get('host') or os.getenv('DB_HOST'),
            'PORT': db_credentials.get('port', '5432') or os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DJOSER={"USER_ID_FIELD":"username"}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}


# =========================================================================
# STATIC & MEDIA ASSET PERIMETER STORAGE (S3 + CloudFront Integration)
# =========================================================================
# Django finds assets inside 'restaurant/static/' automatically during collectstatic
STATICFILES_DIRS = [] 

# If USE_S3 is enabled by the Lambda Environment, rewrite the storage engine
if os.getenv('USE_S3', 'False') == 'True':
    # AWS Credentials injected via Lambda Execution Role (No hardcoded keys!)
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('CLOUDFRONT_DOMAIN_NAME') # e.g., api.asgardcuisines.com
    
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    
    # Configure django-storages backend drivers
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        },
    }
    
    # URL generated by templates {% static '...' %} points directly to the CloudFront Distribution
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
else:
    # Fallback configuration for running locally on your machine
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')